### ISSUE TITLE
Problems encountered during training

### ISSUE THREAD

**Issue by ZWXCV** [godHhh/TPTrack#2]
Hello author, when I was training the mot17 test model, the following error occurred:
Traceback (most recent call last):
File "tools/track.py", line 22, in <module>
from GlLink.ModelLink import *
File "/17106/zwx/TPTrack-main/GlLink/ModelLink.py", line 9, in <module>
import GlLink.config as cfg
ModuleNotFoundError: No module named 'GlLink.config'

I did not find config in the GlLink folder, may I ask how I can solve this problem? Looking forward to the author's reply, thank you very much

**Comment by godHhh** [comment]
Hi, I fixed the issue, please try pulling the code again.

**Comment by ZWXCV** [comment]
Thank you very much for your reply, the problem has been solved
