### ISSUE TITLE
Problems encountered in performing the evaluation

### ISSUE THREAD

**Issue by ZWXCV** [godHhh/TPTrack#3]
Hello author, when I was training the mot17 test model, the following error occurred:
2023-12-04 11:59:56 | ERROR    | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (28907), thread 'MainThread' (139907003770688):
Traceback (most recent call last):

  File "tools/track.py", line 316, in <module>
    launch(
    └ <function launch at 0x7f3d00876550>

> File "/17106/zwx/TPTrack-main/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x7f3c5b061160>

  File "tools/track.py", line 231, in main
    GPRInterpolation(path_in=file_result_name, path_out=file_result_name, interval=20, tau=10)
    │                        │                          └ './YOLOX_outputs/yolox_x_mix_det/track_results/MOT17-08-DPM.txt'
    │                        └ './YOLOX_outputs/yolox_x_mix_det/track_results/MOT17-08-DPM.txt'
    └ <function GPRInterpolation at 0x7f3c5b6b23a0>

  File "/17106/zwx/TPTrack-main/tools/GPRI.py", line 59, in GPRInterpolation
    GPRI = GaussianSmooth(li, tau)
           │              │   └ 10
           │              └ array([[ 1.000e+00,  1.976e+03,  5.464e+02, ..., -1.000e+00, -1.000e+00,
           │                        -1.000e+00],
           │                       [ 2.000e+00,  1.976e+03,...
           └ <function GaussianSmooth at 0x7f3c5bb7caf0>

  File "/17106/zwx/TPTrack-main/tools/GPRI.py", line 43, in GaussianSmooth
    xx = gpr.predict(t)[:, 0]
         │   │       └ array([[266.],
         │   │                [267.],
         │   │                [268.],
         │   │                [269.],
         │   │                [270.],
         │   │                [271.],
         │   │                [272.],
         │   │                [273.],
         │   │              ...
         │   └ <function GaussianProcessRegressor.predict at 0x7f3c5b04cf70>
         └ GaussianProcessRegressor(kernel=RBF(length_scale=14.4))

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

May I ask how I can solve this problem? Looking forward to the author's reply, thank you very much

**Comment by ZWXCV** [comment]
Hello Author May I ask how long did your evaluation procedure on MOT17 take?

**Comment by godHhh** [comment]
> Hello author, when I was training the mot17 test model, the following error occurred: 2023-12-04 11:59:56 | ERROR | yolox.core.launch:90 - An error has been caught in function 'launch', process 'MainProcess' (28907), thread 'MainThread' (139907003770688): Traceback (most recent call last):
> 
> File "tools/track.py", line 316, in launch( └ <function launch at 0x7f3d00876550>
> 
> > File "/17106/zwx/TPTrack-main/yolox/core/launch.py", line 90, in launch
> > main_func(*args)
> > │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
> > │            │ keys  ...
> > └ <function main at 0x7f3c5b061160>
> 
> File "tools/track.py", line 231, in main GPRInterpolation(path_in=file_result_name, path_out=file_result_name, interval=20, tau=10) │ │ └ './YOLOX_outputs/yolox_x_mix_det/track_results/MOT17-08-DPM.txt' │ └ './YOLOX_outputs/yolox_x_mix_det/track_results/MOT17-08-DPM.txt' └ <function GPRInterpolation at 0x7f3c5b6b23a0>
> 
> File "/17106/zwx/TPTrack-main/tools/GPRI.py", line 59, in GPRInterpolation GPRI = GaussianSmooth(li, tau) │ │ └ 10 │ └ array([[ 1.000e+00, 1.976e+03, 5.464e+02, ..., -1.000e+00, -1.000e+00, │ -1.000e+00], │ [ 2.000e+00, 1.976e+03,... └ <function GaussianSmooth at 0x7f3c5bb7caf0>
> 
> File "/17106/zwx/TPTrack-main/tools/GPRI.py", line 43, in GaussianSmooth xx = gpr.predict(t)[:, 0] │ │ └ array([[266.], │ │ [267.], │ │ [268.], │ │ [269.], │ │ [270.], │ │ [271.], │ │ [272.], │ │ [273.], │ │ ... │ └ <function GaussianProcessRegressor.predict at 0x7f3c5b04cf70> └ GaussianProcessRegressor(kernel=RBF(length_scale=14.4))
> 
> IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
> 
> May I ask how I can solve this problem? Looking forward to the author's reply, thank you very much

Hello, I am sorry that I have never encountered such a problem, may I ask if you have solved it?

**Comment by godHhh** [comment]
> Hello Author May I ask how long did your evaluation procedure on MOT17 take?

Just a few minutes on a 3090 GPU.

**Comment by ZWXCV** [comment]
Hello, author, I modified the error part of the code, from xx = gpr.predict(t)[:, 0] to xx = gpr.predict(t), the program runs successfully, but it takes several hours, I think there may be a problem.

**Comment by bdpk123** [comment]
Hello,can you show me where is the CMC and NSA？

**Comment by godHhh** [comment]
> Hello,can you show me where is the CMC and NSA？

The code has been updated. 
CMC is at line 190 in the mot_evaluator.py, and NSA is at line 150 in the kalman_filter.py.

**Comment by godHhh** [comment]
> Hello, author, I modified the error part of the code, from xx = gpr.predict(t)[:, 0] to xx = gpr.predict(t), the program runs successfully, but it takes several hours, I think there may be a problem.

I'm sorry, I have not encountered such an issue before.
